package com.heavystudio.helpabroad.data.local.model

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Represents a country entity in the local database.
 *
 * This data class is used by Room to create the "countries" table. Each entry represents a
 * country, identified by its unique ISO code.
 *
 * @property id The unique identifier for the country entry, auto-generated by the database.
 * @property isoCode The ISO 3166-1 alpha-2 code of the country (e.g., "US", "DE"). This is unique.
 *
 * @author Heavy Studio.
 * @since 0.1.0 Creation of the entity.
 */
@Entity(
    tableName = "countries",
    indices = [Index(value = ["iso_code"], unique = true)]
)
data class CountryEntity(
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    val id: Int = 0,

    @ColumnInfo(name = "iso_code")
    val isoCode: String
)
