package com.heavystudio.helpabroad.data.local.model

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey


/**
 * Represents a single emergency phone number entry in the local database.
 * This entity links a specific phone number to a country and a type of emergency service.
 *
 * @property id The unique identifier for the emergency number entry. Auto-generated by the database.
 * @property countryId The foreign key referencing the country this emergency number belongs to.
 *                     See [CountryEntity].
 * @property serviceTypeId The foreign key referencing the type of emergency service this number is for
 *                         (e.g., Police, Ambulance, Fire). See [EmergencyServiceTypeEntity].
 * @property phoneNumber The actual emergency phone number as a string.
 * @property description An optional description or note about the emergency number.
 *
 * @author Heavy Studio.
 * @since 0.1.0 Creation of the entity.
 */
@Entity(
    tableName = "emergency_numbers",
    foreignKeys = [
        ForeignKey(
            entity = CountryEntity::class,
            parentColumns = ["id"],
            childColumns = ["country_id"],
            onDelete = ForeignKey.CASCADE
        ),
        ForeignKey(
            entity = EmergencyServiceTypeEntity::class,
            parentColumns = ["id"],
            childColumns = ["service_type_id"],
            onDelete = ForeignKey.CASCADE
        )
    ]
)
data class EmergencyNumberEntity(
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "id")
    val id: Int = 0,

    @ColumnInfo(name = "country_id", index = true)
    val countryId: Int,

    @ColumnInfo(name = "service_type_id", index = true)
    val serviceTypeId: Int,

    @ColumnInfo(name = "phone_number")
    val phoneNumber: String,

    @ColumnInfo(name = "description")
    val description: String? = null,

    @ColumnInfo(name = "number_type", defaultValue = "CALL")
    val numberType: String
)
